### PR TITLE
Add MPS support

### PR DESCRIPTION
**Pull request by killianeletellier**
This pull request adds MPS support to the diarization process.
It makes this step of the execution much faster on Apple Silicon Macs.

### CODE REVIEW

**Review by NavodPeiris — COMMENTED** [review]
have you tested it in a mac?

**Comment by killianeletellier** [comment]
Hey,
Yes. 

It needs to add `PYTORCH_ENABLE_MPS_FALLBACK=1` as an environment variable, but the diarization is more than 100 times faster.

**Comment by NavodPeiris** [comment]
then you have to set that environment variable in python script
```
import os

os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
```

**Comment by killianeletellier** [comment]
Oh, yes ! You're right !

I added it locally, but it seems like it committed too soon !

**Comment by NavodPeiris** [comment]
seems all good. Thank you for contributing!!

**Pull request merged**
